version: "3.9"

services:
  btceur:
    build:
      context: .
    container_name: btceur
    volumes:
      - ./market/btceur/config.json:/app/config.json
      - ./market/btceur/pycryptobot.log:/app/pycryptobot.log
      - ./market/btceur/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure

  etheur:
    build:
      context: .
    container_name: etheur
    volumes:
      - ./market/ETHEUR/config.json:/app/config.json
      - ./market/ETHEUR/pycryptobot.log:/app/pycryptobot.log
      - ./market/ETHEUR/graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
