version: "3"

services:
  pycryptobot:
    image: ghcr.io/whittlem/pycryptobot:latest
    container_name: pycryptobot
    volumes:
      - ./config.json:/app/config.json
      - ./graphs:/app/graphs
      - /etc/localtime:/etc/localtime:ro
#
# You can also run multiple containers for each trading pair:
#
#  pycryptobot_btceur:
#    image: ghcr.io/whittlem/pycryptobot:latest
#    container_name: pycryptobot
#    volumes:
#      - ./config_btceur.json:/app/config.json
#      - ./graphs:/app/graphs
#      - /etc/localtime:/etc/localtime:ro
#
#  pycryptobot_etheur:
#    image: ghcr.io/whittlem/pycryptobot:latest
#    container_name: pycryptobot
#    volumes:
#      - ./config_etheur.json:/app/config.json
#      - ./graphs:/app/graphs
#      - /etc/localtime:/etc/localtime:ro
